#!/bin/bash

# Confirmation
dir="~/.config/rofi/styles"
confirm_exit() {
    rofi -dmenu\
        -i\
        -no-fixed-num-lines\
        -p "Are You Sure? : "\
        -theme $dir/confirm.rasi
    }

# Message
msg() {
    rofi -theme "$dir/message.rasi" -e "Available Options  -  yes / y / no / n"
}

ans=$(confirm_exit &)
if [[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]]; then
    case $1 in
        p)
            # Poweroff
            systemctl poweroff
            ;;
        r)
            # Reboot
            systemctl reboot
            ;;
        l)
            # Lock Screen
            if [[ -f /usr/bin/i3lock ]]; then
                i3lock
            elif [[ -f /usr/bin/betterlockscreen ]]; then
                betterlockscreen -l
            fi
            ;;
        h)
            eww close-all
			loginctl suspend
            if [[ -f /usr/bin/i3lock ]]; then
                i3lock
            elif [[ -f /usr/bin/betterlockscreen ]]; then
                betterlockscreen -l
            fi
            ;;
        e)
            # Logout
            if [[ "$DESKTOP_SESSION" == "Openbox" ]]; then
                openbox --exit
            elif [[ "$DESKTOP_SESSION" == "bspwm" ]]; then
                bspc quit
            elif [[ "$DESKTOP_SESSION" == "i3" ]]; then
                i3-msg exit
            fi
            ;;
    esac
    killall eww
    loginctl suspend
    betterlockscreen -l
elif [[ $ans == "no" || $ans == "NO" || $ans == "n" || $ans == "N" ]]; then
    exit 0
else
    msg
fi
