#!/bin/bash

#   ┌───────────────────────────────┐
#   │                               │
#   │       Colors Variables        │
#   │                               │
#   └───────────────────────────────┘

COLOR_NC='\e[0m' # No Color
COLOR_BLACK='\e[0;30m'
COLOR_GRAY='\e[1;30m'
COLOR_RED='\e[0;31m'
COLOR_LIGHT_RED='\e[1;31m'
COLOR_GREEN='\e[0;32m'
COLOR_LIGHT_GREEN='\e[1;32m'
COLOR_BROWN='\e[0;33m'
COLOR_YELLOW='\e[1;33m'
COLOR_BLUE='\e[0;34m'
COLOR_LIGHT_BLUE='\e[1;34m'
COLOR_PURPLE='\e[0;35m'
COLOR_LIGHT_PURPLE='\e[1;35m'
COLOR_CYAN='\e[0;36m'
COLOR_LIGHT_CYAN='\e[1;36m'
COLOR_LIGHT_GRAY='\e[0;37m'
COLOR_WHITE='\e[1;37m'

#   ┌───────────────────────────────┐
#   │                               │
#   │       Program Variables       │
#   │                               │
#   └───────────────────────────────┘

repoconfigdir="$PWD/configs"
userconfigdir="$HOME/.config"

url_packages_raw="https://gist.githubusercontent.com/SergioRibera/c30e826d7ada4a8385ac9b04a732bbb5/raw/f58dd07db02b1168a1427bb44cca0dda9034c057/packages"
packages=$(curl -s $url_packages_raw | tr "\n" " ")

set -e

install_basic_packages() {
    echo -e "${COLOR_BLUE}Installing$COLOR_NC '$packages'"
    paru --skipreview --cleanafter --noconfirm -Sy $packages
}

link_all_config() {
    for f in $repoconfigdir/*; do
        filename=$(basename $f)
        echo -e "${COLOR_PURPLE}Linking Config${COLOR_NC}: $filename"
        ln -s $f "$userconfigdir/$filename"
    done
    echo -e "${COLOR_PURPLE}Linking scripts${COLOR_NC}"
    ln -s "$PWD/scripts $HOME/.config/scripts"
    echo -e "${COLOR_PURPLE}Linking Git Config${COLOR_NC}"
    ln -s "$PWD/.gitconfig $HOME/.gitconfig"
}

install_basic_packages
link_all_config
