#!/bin/bash

values=$(zenity --forms --title "File Details to save" --add-entry="File Name" --add-combo="File Type" --combo-values="png|jpg|svg" --add-combo="File Size" --combo-values="original|2560|1920|1280|640")

path=$1

filename=$(echo "$values" | cut -d'|' -f1)
fileformat=$(echo "$values" | cut -d'|' -f2)
size=$(echo "$values" | cut -d'|' -f3)

if [ fileformat -eq png || fileformat -eq jpg || fileformat -eq svg ]; then
    if [ size = original ]; then
        xclip -selection c -o -t "image/$fileformat" > "$path/$filename.$fileformat"
    else
        xclip -selection c -o -t "image/$fileformat" | convert -resize $size\> - "$path/$filename.$fileformat"
    fi
else
    xclip -selection c -o > "$path/$filename.$fileformat"
fi
