#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Check if wallpaper pid file exist
if [ -f $SCRIPTPATH/wallpaper.pid ]; then
    kill -9 `cat $SCRIPTPATH/wallpaper.pid`
    rm -fr $SCRIPTPATH/wallpaper.pid
fi

if [ -f $SCRIPTPATH/wallpaper.pipe ]; then
    rm -fr $SCRIPTPATH/wallpaper.pipe
fi

kill -9 ~/.config/scripts/screens
kill -9 ~/.config/scripts/battery-status

kill -9 udiskie
kill -9 dunst
kill -9 thunar
kill -9 sbbw

leftwm command "UnloadTheme"
