#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
$SCRIPTPATH/down

# start picom
if [ -f ~/.config/picom/picom.conf ]; then
    if [ -x  "$(command -v picom)" ]; then
        picom -b --xrender-sync-fence --config ~/.config/picom/picom.conf
    fi
fi

# Load random wallpaper
wallpaper -t 30m --volume 25 -s '1' --no-allow-video -d -b &

# Load Theme
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe
