#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
$SCRIPTPATH/down

~/.config/scripts/screens
~/.config/scripts/battery-status &

udiskie &
dunst &
thunar --daemon &
numlockx on

# start picom
if [ -f ~/.config/picom/picom.conf ]; then
    if [ -x  "$(command -v picom)" ]; then
        picom -b --experimental-backends --config ~/.config/picom/picom.conf
    fi
fi

sbbw --quiet run

# Load random wallpaper
wallpaper -t 30m --volume 25 -s '1' --no-allow-video -d -b &

# Load Theme
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"
