#!/usr/bin/env bash

function calc { awk "BEGIN { print "$*" }"; }

function get_brightness {
    brightnessctl get
}

function get_max_brightness {
    brightnessctl max
}

function send_notification {
    # tm_brightness=$(exp get_brightness / get_max_brightness)
    a=$(calc $(get_brightness)/$(get_max_brightness))
    b=$(calc $a*100)
    brightness=${b%.*}
    echo "brightness: $brightness"

    if [ "$brightness" = "0" ]; then
        icon_name="notification-display-brightness-off"
    else
        if [  "$brightness" -lt "10" ]; then
            icon_name="notification-display-brightness-low"
        else
            if [ "$brightness" -lt "30" ]; then
                icon_name="notification-display-brightness-low"
            else
                if [ "$brightness" -lt "70" ]; then
                    icon_name="notification-display-brightness-medium"
                else
                    icon_name="notification-display-brightness-high"
                fi
            fi
        fi
    fi
    # bar=$(seq -s "─" $(($brightness/5)) | sed 's/[0-9]//g')
    # Send the notification
    dunstify "Brightness" "" -I "$icon_name" -t 2000 -h int:value:"$brightness" -r 5555 &>/dev/null
}

case $1 in
    up)
        brightnessctl set +10 > /dev/null
        send_notification
        ;;
    down)
        brightnessctl set 10- > /dev/null
        send_notification
        ;;
esac
