#!/bin/bash

SCREENS=($(xrandr | grep -e ' connected' | sed -e 's/ primary//g' | cut -d" " -f1))

autorandr --change &>> /tmp/bspwm_log.txt

# Disable any form of screen saver / screen blanking / power management
xset s off
xset s noblank
xset -dpms
xrdb -merge ~/.Xresources                                              
xsetroot -cursor_name left_ptr

i=1
printf '%s\n' "${SCREENS[@]}" >> /tmp/bspwm_log.txt

for screen in $SCREENS; do
    bspc monitor $screen -n $screen -d 1 2 3 4 5 6 7 8 9 10
    let i++
done
