#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output HDMI-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VGA-1 --mode 1024x768 --pos 1920x0 --rotate normal --output VIRTUAL1 --off &

compton --config /dev/null --backend glx --blur-method kawase --blur-background --blur-strength 12 &
wname L3GD &
# Set Backgrounds Randoms
/home/sergioribera/.config/nitrogen/autobg.py -c "/home/sergioribera/.config/nitrogen/bg-saved.cfg" -d "/home/sergioribera/Imágenes/Backgrounds/" &
/home/sergioribera/.config/polybar/launch.sh &
dunst &

# Leader Key
bspc config pointer_modifier mod1

bspc monitor HDMI-1 -d I II III IV V
bspc monitor VGA-1 -d VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
