#! /bin/sh

# setxkbmap -model pc105 -layout latam,us -variant deadtilde, -option grp:ctrl_alt_toggle;
# setxkbmap -model pc105 -layout latam,us -variant deadtilde, ;
# Set monitor layout

~/.config/scripts/screens
~/.config/scripts/battery-status &

# Set Backgrounds Randoms
wallpaper -t 30m --volume 25 -s '1' --no-allow-video -d -b &

sxhkd &
udiskie &
dunst &
thunar --daemon &

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

###---Coloring---###
bspc config normal_border_color "#222d32"
bspc config active_border_color "#42565a"
bspc config focused_border_color "#89ddff"
bspc config presel_feedback_color "#42565a"

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 0
bspc config window_gap 3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_monitor true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Glava manage=off
bspc rule -a Discord state=floating follow=on
bspc rule -a UnityHub state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Dolphin state=floating
bspc rule -a Thunar state=floating
bspc rule -a Plank layer=above manage=on border=off
bspc rule -a scrcpy state=floating follow=on
bspc rule -a "bevy*" monitor=2 desktop="^5" follow=on
bspc rule -a zoom state=floating center=on
bspc rule -a "_NET_WM_STATE_ABOVE" state=floating

# Set Picom as Default Compositor
picom -b --experimental-backends --config ~/.config/picom/picom.conf
sbbw --quiet run

# run all desktop files on autostart
for desktop in ~/.config/autostart/*.desktop; do
    if [ -f "$desktop" ]; then
        exo-open $desktop
    fi
done &
